### ISSUE TITLE
Please consider node-red-contrib- naming guidelines

### ISSUE THREAD

**Issue by knolleary** [cuongquay/node-red-contrib-selenium-webdriver#1]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by cuongquay** [comment]
I have just corrected it as you suggested. Many thanks!

**Comment by knolleary** [comment]
Thanks 👍
