### ISSUE TITLE
click-on and findElement nodes goes into locating state without ever returning, rendering the whole flow inusable

### ISSUE THREAD

**Issue by mrummuka** [cuongquay/node-red-contrib-selenium-webdriver#2]
I've experimented a while how the node-red-contrib-selenium-webdriver works using 

> docker run -d -P --name selenium-hub selenium/hub
> docker run -d --name node-chrome --link selenium-hub:hub selenium/node-chrome
> docker run -d -P --name node-red --link selenium-hub:hub cuongquay/node-red-ui-automation

and got the provided example working after replacing the google button label text to local language.
However, when trying to use this for logging in to another site (i.e. setting form values and submitting the form by clicking a button), I get the whole flow to 'hang' very easily by trying different cssSelectors in find object or click on buttons. What happens, is that the flow executes fine until the node in question (click on or find object) executes and turns into "selecting" status, and remains there without timeouting.
Also, redeploying the flow / re-running the flow does not any more  work after this has occurred. 

I suspect that the node-chrome webdriver has crashed or gone into non-recoverable state, or it has simply thrown some error that node-red-contrib-selenium-webdriver is unable to handle.

**Comment by cuongquay** [comment]
I would thank you so much for your deeply experiment in this node. While using this code I also faces with some issues and try to overcome by increasing the wait and timeout factors. For docker use you should enable --restart=always flag to make sure it will up again after crashed.

I would prefer some pull requests from anyone who want to contribute any fixes or improvements.
