### ISSUE TITLE
palette items didn't appear with npm install

### ISSUE THREAD

**Issue by carchrae** [cuongquay/node-red-contrib-selenium-webdriver#3]
when i installed this library using npm (inside the .node-red dir) the palette notes didn't appear.  when i went to manage palette, the UI would not allow me to enable the nodes.  however, by installing via the 'install' tab in manage palette, the nodes appeared as expected.

i was using v0.2.11, other version info below

```
29 Nov 12:03:08 - [info] Node-RED version: v0.15.2
29 Nov 12:03:08 - [info] Node.js  version: v4.5.0
29 Nov 12:03:08 - [info] Linux 4.4.0-24-generic x64 LE
```

**Comment by carchrae** [comment]
i believe this problem (and others) are caused by using an earlier version of node.  switching to 6.9.x and the problems go away - i think because your library depends on selenium-webdriver, which specifies the node version in package.json

```
  "engines": {
    "node": ">= 6.9.0"
  },
```

**Comment by cuongquay** [comment]
Thank you for your analyzing, I will put the required node version into the package setting.

**Comment by carchrae** [comment]
I found another version issue with is-reachable.  version 2.x of this
module only supports promises.  I will make a pull request, or you can lock
it to 1.x

**Comment by cuongquay** [comment]
I would appreciate if you can make a pull request on any issue :+1:

**Comment by carchrae** [comment]
no problem.  PR submitted.  the is-reachable issue had me stumped for ages (because the code crashed silently).  perhaps there is a better way to run node-red with more debug info/exception catching?  i am very new to node-red, so i found the bug by adding lots of console.log to see where it was dying.

**Comment by carchrae** [comment]
fixed by https://github.com/cuongquay/node-red-contrib-selenium-webdriver/commit/0baf9fb3008afff0a6bce32cb559ceac60ff7178
