### ISSUE TITLE
CSS Selektor usage: TypeError: By[node.selector] is not a function

### ISSUE THREAD

**Issue by fschirinzi** [cuongquay/node-red-contrib-selenium-webdriver#6]
When I use the CSS Selektor, I get this error:

## ERROR
`
TypeError: By[node.selector] is not a function
    at Timeout._onTimeout (/root/.node-red/node_modules/node-red-contrib-selenium-webdriver/selenium-webdriver.js:94:61)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
`

## Flow Sample
`
[{"id":"775c6b5d.01eb84","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"4cad1e52.e457c","type":"function","z":"775c6b5d.01eb84","name":"ErrorHandle","func":"if (msg.error) {\n    msg.statusCode = 400;\n    msg.payload = msg.error;\n}\nreturn msg;","outputs":1,"noerr":0,"x":1314,"y":229,"wires":[["edda0c10.9db96"]]},{"id":"318291a6.7e9afe","type":"inject","z":"775c6b5d.01eb84","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"x":584,"y":149,"wires":[["bb4063fc.7287"]]},{"id":"edda0c10.9db96","type":"debug","z":"775c6b5d.01eb84","name":"","active":true,"console":"false","complete":"false","x":1474,"y":229,"wires":[]},{"id":"bb4063fc.7287","type":"open-web","z":"775c6b5d.01eb84","name":"","browser":"firefox","weburl":"https://www.google.com/","width":"480","height":"640","webtitle":"Google","timeout":"3000","maximized":true,"server":"2669fd73.b82f12","x":754,"y":149,"wires":[["faefcf64.2e188"]]},{"id":"47fc88fd.6fdb08","type":"close-web","z":"775c6b5d.01eb84","name":"","waitfor":"1500","x":1154,"y":229,"wires":[["4cad1e52.e457c"]]},{"id":"12979d14.f1c8f3","type":"delay","z":"775c6b5d.01eb84","name":"","pauseType":"delay","timeout":"1","timeoutUnits":"seconds","rate":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"x":1004,"y":229,"wires":[["47fc88fd.6fdb08"]]},{"id":"faefcf64.2e188","type":"find-object","z":"775c6b5d.01eb84","name":"","selector":"name","target":"btnK","timeout":"1000","waitfor":"1500","x":944,"y":149,"wires":[["6c674ceb.1bb454"]]},{"id":"6c674ceb.1bb454","type":"get-value","z":"775c6b5d.01eb84","name":"CheckButton","expected":"Google-Suche","selector":"name","target":"btnK","timeout":"1000","waitfor":"1500","savetofile":false,"x":1134,"y":149,"wires":[["4e7f1c42.718cf4"]]},{"id":"4e7f1c42.718cf4","type":"send-keys","z":"775c6b5d.01eb84","name":"","text":"cuongdd1","selector":"xpath","target":"//*[@id=\"lst-ib\"]","timeout":"1000","waitfor":"1500","clearval":false,"x":1314,"y":149,"wires":[["a4fc409f.5d27a"]]},{"id":"96a38194.84529","type":"click-on","z":"775c6b5d.01eb84","name":"","selector":"cssSelector","target":"\"input[name=btnG]\"","timeout":"10000","waitfor":"1500","clickon":false,"x":664,"y":229,"wires":[["280270b9.8fee9"]]},{"id":"280270b9.8fee9","type":"run-script","z":"775c6b5d.01eb84","name":"","func":"\nreturn arguments[0].innerHTML;","selector":"name","target":"","timeout":"10000","waitfor":"1500","x":834,"y":229,"wires":[["12979d14.f1c8f3"]]},{"id":"5b1ad083.7ba7e","type":"link in","z":"775c6b5d.01eb84","name":"","links":["a4fc409f.5d27a"],"x":519,"y":229,"wires":[["96a38194.84529"]]},{"id":"a4fc409f.5d27a","type":"link out","z":"775c6b5d.01eb84","name":"","links":["5b1ad083.7ba7e"],"x":1439,"y":149,"wires":[]},{"id":"2669fd73.b82f12","type":"selenium-server","z":"775c6b5d.01eb84","remoteurl":"http://localhost:4444/wd/hub"}]
`

**Comment by uli6** [comment]
Same error here. :(
